### ISSUE TITLE
Under construction page

### ISSUE THREAD

**Issue by tomagb** [AZS-CJ/AdventistClujRO#20]
Create a page for react which is the default landing page.
The page should mention that the site is in construction.
The page should mention a contact email or phone number. Ask Daniel Tomoiaga what details to add there.
The page should be enabled by default. There should be a mechanism which can disable this. The reason is to have it on the production web site but disabled on the development web site.
There should be a link to facebook page.

Add a new file called UnderConstruction.tsx
In it copy the return statement from React component.
In the return statement create the html for the construction page to look like the files provided in the attachements below.
If there is anything asset file (png, etc.) add it in public folder.
Modify the App function so that it returns the UnderConstruction page.

**Comment by Viktorens** [comment]
This is the design I made for the under construction page.

[2021101901_under_construction_page.zip](https://github.com/AZS-CJ/AdventistClujRO/files/7378763/2021101901_under_construction_page.zip)

**Comment by Viktorens** [comment]
[This](https://github.com/Viktorens/Biserica-Speranta-Under-Construction-Web-Page) is the under construction page I made.
I also hosted it [here](https://reverent-mccarthy-6148b2.netlify.app/), to check its responsiveness.

**Comment by tomagb** [comment]
Done.
