### ISSUE TITLE
Design for home page

### ISSUE THREAD

**Issue by tomagb** [AZS-CJ/AdventistClujRO#32]

**Comment by Viktorens** [comment]
Hello!
[Aici](https://xd.adobe.com/view/0818cac6-e409-4181-a2a1-9b03fd13b38b-5d4b/) gasiti design-ul homepage-ului. Meniul ca design va fii similar. Inca lucrez la el...nu cred ca o sa il termin anul acesta.

**Comment by tomagb** [comment]
Done.
