### ISSUE TITLE
Create/Style menu

### ISSUE THREAD

**Issue by bettyMelania** [AZS-CJ/AdventistClujRO#35]
![WhatsApp Image 2021-12-14 at 23 02 06](https://user-images.githubusercontent.com/26300421/147065873-a109735c-b912-4911-a456-a34dcd9669c0.jpeg)

**Comment by bettyMelania** [comment]
new version: https://xd.adobe.com/view/0818cac6-e409-4181-a2a1-9b03fd13b38b-5d4b/

**Comment by tomagb** [comment]
Done.
