### ISSUE TITLE
Bug when uploading images to local cms and adventistclujro-strapi-test

### ISSUE THREAD

**Issue by bettyMelania** [AZS-CJ/AdventistClujRO#57]
Steps to reproduce:
1. Run strapi cms locally
2. Run https://adventistclujro-strapi-test.azurewebsites.net/admin/
3. Add content to Background -> home (upload an image)
4. Check the same content on local cms, the image is missing
5. Upload another image to Background -> home on local cms
6. Check adventistclujro-strapi-test Content -> now the home image is not loading in Content
* If you update a text/date adventistclujro-strapi-test/local cms the changes happen as exepected

**Comment by tomagb** [comment]
Solved by introducing Azure Storage File share for the path where strapi is keeping its binary files.
