### ISSUE TITLE
Frontend customizable fields

### ISSUE THREAD

**Issue by Viktorens** [AZS-CJ/AdventistClujRO#97]
Add customizable fields:
- 4 colors (primary color, accent color, second shade for primary color, second shade for accent color) - Betty 
- texts (church address, contact page and footer) - Alex
- navbar church logo  - Alex
- social media links - Alex
- flag for Live button - 
- custom live link in BE -

**Comment by Alexandru736** [comment]
Can't run strapi when I run `npm run start` in cmsstrapi
Had error with running `yarn install` due to higher node version
Can't edit the entity models to add new fields

**Comment by bettyMelania** [comment]
1. For running the db locally, you need to run in development mode: "yarn develop" in cmsstrapi folder
Also you need to install mysql and put your connection data in the .env file in the cmsstrapi folder
2. yes, I use node 16, and I use nvm to change the node version for my different projects
3. After you run the db locally you can edit the fields and types in the "Content-Type Builder"
